services:
  - type: web
    name: designmecha-mes-backend
    runtime: python
    region: singapore
    plan: free
    branch: main
    rootDir: backend
    buildCommand: ./build.sh
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mes-db
          property: connectionString
      - key: BACKEND_CORS_ORIGINS
        value: "[\"*\"]"

databases:
  - name: mes-db
    region: singapore
    plan: free
    databaseName: mes_erp
    user: mes_user

